trigger:
  branches:
    include:
      - master
  paths:
    include:
      - ./services/discovery-service
variables: []
stages:
  - stage: build
    jobs:
      - job: run_build_push_acr
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |-
              echo "az login --service-principal --username $(SP_APP_ID) --password $(SP_PASS) --tenant $(SP_TENANT)"
              az login --service-principal --username "$(SP_APP_ID)" --password "$(SP_PASS)" --tenant "$(SP_TENANT)"
            displayName: Azure Login
          - script: |-
              cd ./services/discovery-service
              echo "az acr build -r $(ACR_NAME) --image $(Build.Repository.Name)-discovery-service:$(Build.SourceBranchName)-$(Build.BuildNumber) ."
              az acr build -r $(ACR_NAME) --image $(Build.Repository.Name)-discovery-service:$(Build.SourceBranchName)-$(Build.BuildNumber) .
            displayName: ACR Build and Publish
  - stage: hld_update
    dependsOn: build
    condition:
      "and(succeeded('build'), or(startsWith(variables['Build.SourceBranch'],
      'refs/heads/DEPLOY/'),eq(variables['Build.SourceBranchName'],'master')))"
    jobs:
      - job: update_image_tag
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |-
              # Download build.sh
              curl https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/build.sh > build.sh
              chmod +x ./build.sh
            displayName: Download bedrock bash scripts
          - script: |-
              # --- From https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/release.sh
              . build.sh --source-only

              # Initialization
              verify_access_token
              init
              helm init

              # Fabrikate
              get_fab_version
              download_fab

              # Clone HLD repo
              git_connect
              # --- End Script

              # Update HLD
              git checkout -b "DEPLOY/$(Build.Repository.Name)-discovery-service-$(Build.SourceBranchName)-$(Build.BuildNumber)"
              ../fab/fab set --subcomponent discovery-service image.tag=$(Build.SourceBranchName)-$(Build.BuildNumber)
              echo "GIT STATUS"
              git status
              echo "GIT ADD (git add -A)"
              git add -A

              # Set git identity
              git config user.email "admin@azuredevops.com"
              git config user.name "Automated Account"

              # Commit changes
              echo "GIT COMMIT"
              git commit -m "Updating discovery-service image tag to $(Build.SourceBranchName)-$(Build.BuildNumber)."

              # Git Push
              git_push

              # Open PR via az repo cli
              echo 'az extension add --name azure-devops'
              az extension add --name azure-devops

              echo 'az repos pr create --description "Updating discovery-service to $(Build.SourceBranchName)-$(Build.BuildNumber)."'
              az repos pr create --description "Updating discovery-service to $(Build.SourceBranchName)-$(Build.BuildNumber)."
            displayName: "Download Fabrikate, Update HLD, Push changes, Open PR"
            env:
              ACCESS_TOKEN_SECRET: $(PAT)
              AZURE_DEVOPS_EXT_PAT: $(PAT)
              REPO: $(HLD_REPO)
